### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by sls-mdr** [jb-ds2020/nf-ds3-capstone-churn-prevention#16]
- [x] Missings
- [x] head - sample - tail
- [x] Dublicates
- [x] Skew / Range
- [x] Feature type (cat or cont)
- [x] Classes (user data, traffic data...)
- [x] check nulls (relative)
- [x] Analyse and evaluate time related features
- [x] Drops?
- [x] Balance 1:4
- [x] Doku

**Comment by sls-mdr** [comment]
I added a new column to meta df with relativ values of "0" in feature.

**Comment by jb-ds2020** [comment]
I added "Analyse and evaluate time related features"
