### ISSUE TITLE
Github Notebooks (Join + Cleaning)

### ISSUE THREAD

**Issue by jb-ds2020** [jb-ds2020/nf-ds3-capstone-churn-prevention#61]
- [x] Write Text to ML Main Part (Description + Conclusion of the results)

- [x] Machine Learning Notebook:

1. Feature Selection
2. ML Models (+ Optimization)
3. Stacking Classifier

- [x] Folder with relevant model notebooks

**Comment by sls-mdr** [comment]
Text for the models: https://docs.google.com/document/d/1jUy2_PJGlQCkusAISHm1Y_h8xCvijAd68uhe2ENCinY/edit?usp=sharing
